Dev readme
NDCLab/oops-faces-dataset pull request #2
Opened 2022-02-07 19:07 UTC by ylimerm3

2022-02-09 22:03 UTC, jessb0t commented
@ylimerm3 Thank you so much for updating this readme!  I have itemized notes in the review.  Some other comments:
- For contributors, I believe the following would be accurate?

| Role | Name |
| ---  | ---  |
| Project Administration | Emily Martin |
| Supervision | George A. Buzzell, Fabian A. Soto |

- Please delete that 👉  text at the very bottom.
- Please update the contributing.md file.  If you need some inspiration, you can check out [this repo](https://github.com/NDCLab/readAloud-valence-dataset/blob/main/CONTRIBUTING.md).

Thank you! :pray:

2022-02-09 23:02 UTC, jessb0t requested changes
Testing something to make these visible to you!

2022-02-09 23:02 UTC, jessb0t commented on README.md
> +Build on a prior study (Buzzell et al., 2017) that showed after detecting an error, there is a brief reduction in stimulus-evoked activity for the following trial when the RSI is small, applying a fa
Some suggestions here:
- Add hyperlink for the citation, so that a visitor knows exactly which paper.  (Could just be the PubMed link.)
- Is it possible to gently define RSI for those who aren't familiar with the term?  (Like me... :joy:)
- It isn't clear what "applying a face..." connects to.  Maybe two sentences are needed for clarity?

2022-02-09 23:02 UTC, jessb0t commented on README.md
> +Previous work in stimulus discrimination research has found that error detection reduces stimulus-evoked activity for the next trial when the RSI is small, but not when the RSI is large (Buzzell et a
- Same comment as above about citations.
- Please use present tense, which will age better.
- I think you may need to move (or simply remove) "with undergraduates recruited from FIU," which currently modifies "emotional valence" and leads to ambiguity.

2022-02-09 23:02 UTC, jessb0t commented on README.md
> +Stimuli will be created using FaReT, a recent open source toolbox to create realistic computerized face models. See FaReT [here](https://github.com/fsotoc/FaReT).
- Please use present tense.
- Totally a suggestion, but you could put the hyperlink on the first instance of "FaReT" and drop the second sentence altogether.

2022-02-09 23:02 UTC, jessb0t commented on README.md
> +Prior to beginning the study, participants will fill out a series of questionnaires to assess anxiety levels (both generalized and social). Participants will perform a two-choice (counterbalanced) pe
- Please use present tense.
- You mention generalized and social anxiety.  State or trait?
- Can we link to anything useful for the pilot study?

2022-02-09 23:02 UTC, jessb0t commented on README.md
>  ## Roadmap
Love the detail here.  We actually use [ZenHub](https://app.zenhub.com/workspaces/oops-faces-614b593978740e001c4489b7/board?repos=409276755) for this level of detail.  Ping me on Slack if you want a demo of how to put together the ZenHub workspace and use it as a project management tool.

For the purposes of the repo, please just roadmap out the dataset release(s) that are planned.  For instance, you might just say:
**Release:** Q3 2022

2022-02-09 23:02 UTC, jessb0t commented on README.md
> -This `main` branch contains completed releases for this project. For all work-in-progress, please switch over to the `dev` branches.
Actually, can you please revert this to the "This main branch..." sentence?  Our idea is that visitors might come to the repo and find this message, so they would know the look around the other branches to see the PsychoPy work-in-progress, etc.

Speaking of which, please do build on GitHub.  You can create a separate `dev-psychopy` branch, for instance.  This way any collaborator can access your work if you have questions or want a second pair of eyes. :)

2022-02-09 23:10 UTC, ylimerm3 commented on README.md
> +Prior to beginning the study, participants will fill out a series of questionnaires to assess anxiety levels (both generalized and social). Participants will perform a two-choice (counterbalanced) pe
i asked fabian about the link for the pilot study, he doesn't have it posted online yet. we'll have to add the link once he does

2022-02-09 23:24 UTC, ylimerm3 commented on README.md
> +Prior to beginning the study, participants will fill out a series of questionnaires to assess anxiety levels (both generalized and social). Participants will perform a two-choice (counterbalanced) pe
also, i am assuming just trait anxiety, but i'm not sure what the questionnaires george wants me to use... we could also update this later?

2022-02-10 07:34 UTC, ylimerm3 commented
@jessb0t  hi jess, please see my changes & view my replies about the link to the pilot study & which type of anxiety will be assessed.

2022-02-17 18:16 UTC, jessb0t approved these changes
Thanks for the updates, @ylimerm3 !  Merging into `dev` now!

2022-02-17 18:17 UTC, merged